In [1]:
import pandas as pd

In [11]:
df=pd.read_excel(r'C:/Users/Lavanya N/Downloads/Copy of cdda.xlsx')

In [12]:
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I100008,C199951,Male,65,Clothing,5,1500.40,Cash,2022-07-10,Emaar Square Mall
1,I100014,C138893,Male,55,Cosmetics,5,203.30,Cash,2021-06-18,Viaport Outlet
2,I100015,C132779,Female,35,Clothing,2,600.16,Debit Card,2021-03-04,Mall of Istanbul
3,I100024,C244411,Female,67,Books,3,45.45,Credit Card,2023-01-05,Emaar Square Mall
4,I100027,C150002,Female,19,Technology,4,4200.00,Cash,2022-05-18,Mall of Istanbul

In [13]:
df.tail()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
20769,I166531,C512562,Male,47,Clothing,4,1200.32,Credit Card,2022-05-17,Metropol AVM
20770,I166533,C939174,Female,69,Books,5,75.75,Debit Card,2021-02-22,Metropol AVM
20771,I166534,C236779,Male,66,Cosmetics,2,81.32,Debit Card,2023-02-24,Forum Istanbul
20772,I166535,C196814,Male,41,Clothing,5,1500.40,Debit Card,2021-07-22,Forum Istanbul
20773,I166536,C106583,Female,56,Toys,5,179.20,Credit Ca,NaT,NaN

In [14]:
df.describe()

                age     quantity         price                   invoice_date
count  20774.000000  20774.00000  20774.000000                          20773
mean      43.473236      3.00905    682.155235  2022-02-04 09:50:49.246618112
min       18.000000      1.00000      5.230000            2021-01-01 00:00:00
25%       30.000000      2.00000     40.660000            2021-07-20 00:00:00
50%       43.000000      3.00000    203.300000            2022-02-05 00:00:00
75%       57.000000      4.00000   1200.320000            2022-08-22 00:00:00
max       69.000000      5.00000   5250.000000            2023-03-08 00:00:00
std       14.993872      1.41364    938.843432                            NaN

In [17]:
df.isnull().value_counts()

invoice_no  customer_id  gender  age    category  quantity  price  payment_method  invoice_date  shopping_mall
False       False        False   False  False     False     False  False           False         False            20773
                                                                                   True          True                 1
Name: count, dtype: int64

In [18]:
df.isnull().sum()

invoice_no        0
customer_id       0
gender            0
age               0
category          0
quantity          0
price             0
payment_method    0
invoice_date      1
shopping_mall     1
dtype: int64

In [19]:
df[df.isnull().any(axis=1)]

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
20773,I166536,C106583,Female,56,Toys,5,179.2,Credit Ca,NaT,NaN

In [22]:
df.dropna(inplace=True)

In [23]:
df.isnull().sum()

invoice_no        0
customer_id       0
gender            0
age               0
category          0
quantity          0
price             0
payment_method    0
invoice_date      0
shopping_mall     0
dtype: int64

In [24]:
df['payment_method'].value_counts()

payment_method
Cash           9273
Credit Card    7273
Debit Card     4227
Name: count, dtype: int64

In [31]:
df['invoice_no'].duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
20768    False
20769    False
20770    False
20771    False
20772    False
Name: invoice_no, Length: 20773, dtype: bool

In [35]:
df['Purchase_Amount_USD']=df['price']*df['quantity']

In [37]:
features=df[['age', 'Purchase_Amount_USD']]

In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
scaler=StandardScaler()
scaled_features=scaler.fit_transform(features)

In [43]:
from sklearn.cluster import KMeans

In [44]:
kmeans= KMeans(n_clusters=3, random_state=42)
df['Cluster']=kmeans.fit_predict(scaled_features)

In [46]:
df.groupby('Cluster')[['age', 'Purchase_Amount_USD']].mean()

               age  Purchase_Amount_USD
Cluster
0        30.461707          1591.994374
1        56.548483          1620.271151
2        41.993046         14569.945292

In [47]:
df['Cluster'].value_counts()

Cluster
1    9725
0    9610
2    1438
Name: count, dtype: int64